# Generated by Django 3.1.4 on 2021-01-21 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STORE_EMAIL', models.EmailField(max_length=254, null=True, unique=True)),
                ('STORE_NAME', models.CharField(max_length=70)),
                ('STORE_POSTAL_CODE', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('STORE_ADDRESS', models.CharField(max_length=100)),
                ('STORE_TEL', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='StoreMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASS1_ID', models.IntegerField(default=1)),
                ('CLASS1', models.CharField(max_length=50)),
                ('CLASS2_ID', models.IntegerField(default=1)),
                ('CLASS2', models.CharField(max_length=50)),
                ('CLASS3_ID', models.IntegerField(default=1)),
                ('CLASS3', models.CharField(max_length=50)),
                ('PLICE', models.IntegerField()),
                ('STORE_INFO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.storeinfo')),
            ],
        ),
    ]
