# Generated by Django 3.1.4 on 2020-12-24 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STORE_EMAIL', models.EmailField(max_length=254, unique=True)),
                ('STORE_NAME', models.CharField(max_length=70)),
                ('STORE_POSTAL_CODE', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('STORE_ADDRESS', models.CharField(max_length=100)),
                ('STORE_TEL', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
            ],
        ),
    ]
